apiVersion: apps/v1 
kind: Deployment
metadata:
  namespace: rokhnamespace
  name: nginx-deployment
  labels:
    app: nginx

spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0 
      maxSurge: 1

  paused: false 
  selector:
    matchLabels:
      app: nginx

  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: web
          image: nginx:1.19
          ports:
            - containerPort: 80

          # Probs
          startupProbe:
            
            # tcp sockets action
            #tcpSocket:
            #  port: 80


            # http get action
            httpGet:
              port: 80
              path: /
                #httpHeaders:
                #  - name: 
                #    value: 


            # exec action
            #exec:
            #  command:
            #    - cat
            #    - /etc/nginx/nginx.conf

            initialDelaySeconds: 5 
            periodSeconds: 5
            failureThreshold: 5
            successThreshold: 1

          livenessProbe:
            # tcp sockets action
            #tcpSocket:
            #  port: 80
            
            # http get action
            httpGet:
              port: 80
              path: / 

            # exec action
            #exec: 
            #  command:
            #    - cat
            #    - /etc/nginx/nginx.conf
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 5
            successThreshold: 1

          readinessProbe:
            
            httpGet:
              port: 80
              path: /
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 5
            successThreshold: 5


