apiVersion: apps/v1 
kind: Deployment
metadata:
  namespace: rokhnamespace
  name: nginx-deployment
  labels:
    app: nginx

spec:
  replicas: 2
  paused: false 
  selector:
    matchLabels:
      app: nginx

  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: web
          image: nginx:1.18
          ports:
            - containerPort: 80

          # Probs
          startupProbe:
            
            # tcp sockets action
            #tcpSocket:
            #  port: 80


            # http get action
            #httpGet:
            #  port: 80
            #  path: /nginx
                #httpHeaders:
                #  - name: 
                #    value: 


            # exec action
            exec:
              command:
                - cat
                - /etc/nginx/nginx.conf

            initialDelaySeconds: 120
            periodSeconds: 5
            failureThreshold: 5
            successThreshold: 1

          livenessProbe:
            # tcp sockets action
            #tcpSocket:
            #  port: 80
            
            # http get action
            #httpGet:
            #  port: 80
            #  path: /nginx

            # exec action
            exec: 
              command:
                - cat
                - /etc/nginx/nginx.conf
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 5
            successThreshold: 1

          readinessProbe:
            tcpSocket:
              port: 80
            #httpGet:
            #  port: 80
            #  path: /nginx
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 5
            successThreshold: 5


